module.exports = [
  "Acajete",
  "Acateno",
  "Acatlán",
  "Acatzingo",
  "Acteopan",
  "Ahuacatlán",
  "Ahuatlán",
  "Ahuazotepec",
  "Ahuehuetitla",
  "Ajalpan",
  "Albino Zertuche",
  "Aljojuca",
  "Altepexi",
  "Amixtlán",
  "Amozoc",
  "Aquixtla",
  "Atempan",
  "Atexcal",
  "Atlequizayan",
  "Atlixco",
  "Atoyatempan",
  "Atzala",
  "Atzitzihuacán",
  "Atzitzintla",
  "Axutla",
  "Ayotoxco de Guerrero",
  "Calpan",
  "Caltepec",
  "Camocuautla",
  "Caxhuacan",
  "Coatepec",
  "Coatzingo",
  "Cohetzala",
  "Cohuecan",
  "Coronango",
  "Coxcatlán",
  "Coyomeapan",
  "Coyotepec",
  "Cuapiaxtla de Madero",
  "Cuautempan",
  "Cuautinchán",
  "Cuautlancingo",
  "Cuayuca de Andrade",
  "Cuetzalan del Progreso",
  "Cuyoaco",
  "Chalchicomula de Sesma",
  "Chapulco",
  "Chiautla",
  "Chiautzingo",
  "Chiconcuautla",
  "Chichiquila",
  "Chietla",
  "Chigmecatitlán",
  "Chignahuapan",
  "Chignautla",
  "Chila",
  "Chila de la Sal",
  "Honey",
  "Chilchotla",
  "Chinantla",
  "Domingo Arenas",
  "Eloxochitlán",
  "Epatlán",
  "Esperanza",
  "Francisco Z. Mena",
  "General Felipe Ángeles",
  "Guadalupe",
  "Guadalupe Victoria",
  "Hermenegildo Galeana",
  "Huaquechula",
  "Huatlatlauca",
  "Huauchinango",
  "Huehuetla",
  "Huehuetlán el Chico",
  "Huejotzingo",
  "Hueyapan",
  "Hueytamalco",
  "Hueytlalpan",
  "Huitzilan de Serdán",
  "Huitziltepec",
  "Atlequizayan",
  "Ixcamilpa de Guerrero",
  "Ixcaquixtla",
  "Ixtacamaxtitlán",
  "Ixtepec",
  "Izúcar de Matamoros",
  "Jalpan",
  "Jolalpan",
  "Jonotla",
  "Jopala",
  "Juan C. Bonilla",
  "Juan Galindo",
  "Juan N. Méndez",
  "Lafragua",
  "Libres",
  "La Magdalena Tlatlauquitepec",
  "Mazapiltepec de Juárez",
  "Mixtla",
  "Molcaxac",
  "Cañada Morelos",
  "Naupan",
  "Nauzontla",
  "Nealtican",
  "Nicolás Bravo",
  "Nopalucan",
  "Ocotepec",
  "Ocoyucan",
  "Olintla",
  "Oriental",
  "Pahuatlán",
  "Palmar de Bravo",
  "Pantepec",
  "Petlalcingo",
  "Piaxtla",
  "Puebla",
  "Quecholac",
  "Quimixtlán",
  "Rafael Lara Grajales",
  "Los Reyes de Juárez",
  "San Andrés Cholula",
  "San Antonio Cañada",
  "San Diego la Mesa Tochimiltzingo",
  "San Felipe Teotlalcingo",
  "San Felipe Tepatlán",
  "San Gabriel Chilac",
  "San Gregorio Atzompa",
  "San Jerónimo Tecuanipan",
  "San Jerónimo Xayacatlán",
  "San José Chiapa",
  "San José Miahuatlán",
  "San Juan Atenco",
  "San Juan Atzompa",
  "San Martín Texmelucan",
  "San Martín Totoltepec",
  "San Matías Tlalancaleca",
  "San Miguel Ixitlán",
  "San Miguel Xoxtla",
  "San Nicolás Buenos Aires",
  "San Nicolás de los Ranchos",
  "San Pablo Anicano",
  "San Pedro Cholula",
  "San Pedro Yeloixtlahuaca",
  "San Salvador el Seco",
  "San Salvador el Verde",
  "San Salvador Huixcolotla",
  "San Sebastián Tlacotepec",
  "Santa Catarina Tlaltempan",
  "Santa Inés Ahuatempan",
  "Santa Isabel Cholula",
  "Santiago Miahuatlán",
  "Huehuetlán el Grande",
  "Santo Tomás Hueyotlipan",
  "Soltepec",
  "Tecali de Herrera",
  "Tecamachalco",
  "Tecomatlán",
  "Tehuacán",
  "Tehuitzingo",
  "Tenampulco",
  "Teopantlán",
  "Teotlalco",
  "Tepanco de López",
  "Tepango de Rodríguez",
  "Tepatlaxco de Hidalgo",
  "Tepeaca",
  "Tepemaxalco",
  "Tepeojuma",
  "Tepetzintla",
  "Tepexco",
  "Tepexi de Rodríguez",
  "Tepeyahualco",
  "Tepeyahualco de Cuauhtémoc",
  "Tetela de Ocampo",
  "Teteles de Ávila Castillo",
  "Teziutlán",
  "Tianguismanalco",
  "Tilapa",
  "Tlacotepec de Benito Juárez",
  "Tlacuilotepec",
  "Tlachichuca",
  "Tlahuapan",
  "Tlaltenango",
  "Tlanepantla",
  "Tlaola",
  "Tlapacoya",
  "Tlapanalá",
  "Tlatlauquitepec",
  "Tlaxco",
  "Tochimilco",
  "Tochtepec",
  "Totoltepec de Guerrero",
  "Tulcingo",
  "Tuzamapan de Galeana",
  "Tzicatlacoyan",
  "Venustiano Carranza",
  "Vicente Guerrero",
  "Xayacatlán de Bravo",
  "Xicotepec",
  "Xicotlán",
  "Xiutetelco",
  "Xochiapulco",
  "Xochiltepec",
  "Xochitlán de Vicente Suárez",
  "Xochitlán Todos Santos",
  "Yaonáhuac",
  "Yehualtepec",
  "Zacapala",
  "Zacapoaxtla",
  "Zacatlán",
  "Zapotitlán",
  "Zapotitlán de Méndez",
  "Zaragoza",
  "Zautla",
  "Zihuateutla",
  "Zinacatepec",
  "Zongozotla",
  "Zoquiapan",
  "Zoquitlán"
];